Music/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Music.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        Music_DBEntities db = new Music_DBEntities();
        clsMail mail = new clsMail();
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string username, string password)
        {
            try
            {
                Admin ad = db.Admins.Where(a => a.UserName == username && a.Password == password).FirstOrDefault();
                if (ad != null)
                {
                    Session["Admin_Id"] = ad.Admin_Id;
                    return RedirectToAction("Profile");
                }
                else
                { ViewBag.error = "Username or password is invalid"; }
            }
            catch { }
            return View();
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ForgotPassword(string username)
        {
            try
            {
                Admin ad = db.Admins.Where(a => a.UserName == username).FirstOrDefault();
                if (ad != null)
                {
                    mail.mailSend(username, "Forgot Password","Your password is "+ ad.Password.ToString());
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.errorMsg = "Email is not valid.";
                }
            }
            catch { ViewBag.errorMsg = "Technical error."; }
            return View();
        }
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult Profile()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            MainProfile mp = db.MainProfiles.FirstOrDefault();
            return View(mp);
        }
        [HttpPost]
        public ActionResult Profile(int id=0)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            try
            {
                MainProfile mp = db.MainProfiles.FirstOrDefault();
                mp.Name = Request["name"];
                mp.Email = Request["email"];
                mp.ContactNumber = Request["contactnumber"];
                mp.Address = Request["address"];
                mp.CoverProfilePhoto = Request["CoverProfilePhoto"];
                mp.FacebookLink = Request["FacebookLink"];
                mp.YouTubeLink = Request["YouTubeLink"];
                mp.TwiterLink = Request["TwiterLink"];
                mp.Google_Link = Request["Google_Link"];
                mp.About_1 = Request["About_1"];
                db.Entry(mp).State = System.Data.Entity.EntityState.Modified;
                int i = db.SaveChanges();
                if (i > 0)
                { return RedirectToAction("Profile"); }
                else
                { ViewBag.error = "Failed to Update"; }
            }
            catch { }
            return View("Profile");
        }
       
        public ActionResult AdminInfo()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            return View(db.Admins.ToList());
        }
        public ActionResult AdminView(int id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            Admin ad = db.Admins.Find(id);
            Session["Admin_Id"] = id;
            if (ad == null)
            {
                ViewBag.error = "Data Not Found | Technical error";
            }
            return View(ad);
        }
        [HttpPost]
        public ActionResult AdminView()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            
            int id=Convert.ToInt32( Session["Admin_Id"]);
            Admin ad = db.Admins.Find(id);
            try
            {
                if (ad != null)
                {
                    ad.MobileNumber = Request["mobilenumber"];
                    ad.Password = Request["password"];
                    ad.Name = Request["name"];
                    db.Entry(ad).State = System.Data.Entity.EntityState.Modified;
                    int i = db.SaveChanges();
                    if (i > 0)
                    { return RedirectToAction("AdminInfo"); }
                    else
                    { ViewBag.error = "Failed to update";}
                }
            }
            catch{}
            return View(ad);
        }
        public ActionResult AdminDelete(int id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            Admin ad = db.Admins.Find(id);
            Session["Admin_Id"] = id;
            if (ad == null)
            {
                ViewBag.error = "Data Not Found | Technical error";
            }
            return View(ad);
        }
        [HttpPost]
        public ActionResult AdminDelete()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            int id = Convert.ToInt32(Session["Admin_Id"]);
            Admin ad = db.Admins.Find(id);
            try
            {
                if (ad != null)
                {
                    db.Admins.Remove(ad);

                    int i = db.SaveChanges();
                    if (i > 0)
                    { return RedirectToAction("AdminInfo"); }
                    else
                    { ViewBag.error = "Failed to update"; }
                }
            }
            catch { }
            return View(ad);
        }
        public ActionResult AddSongType()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            return View(db.AudioTypes.OrderBy(a=>a.AudioType1).ToList());
        }
        [HttpPost]
        public ActionResult AddSongType(string type)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            try
            {
                AudioType at = new AudioType();
                at.AudioType1 = type;
                db.AudioTypes.Add(at);
                int i = db.SaveChanges();
                if (i > 0)
                { return RedirectToAction("SongCreate"); }
                else
                { ViewBag.error = "Filed to add song type"; }
            }
            catch { ViewBag.error = "Technical Error"; }
            return View();
        }
        public ActionResult EditSongType(int id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            AudioType at=db.AudioTypes.Find(id);
            Session["AudioType_Id"]=id;
            if (at == null)
            {
                ViewBag.error = "Data Not Found | Technical error";
            }
            return View(at);
        }
        [HttpPost]
        public ActionResult EditSongType()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
                int id = Convert.ToInt32(Session["AudioType_Id"]);
                AudioType at = db.AudioTypes.Find(id);
                if (at != null)
                {
                    at.AudioType1 = Request["type"];
                    db.Entry(at).State = System.Data.Entity.EntityState.Modified;
                    int i = db.SaveChanges();
                    if (i > 0)
                    {
                        return RedirectToAction("AddSongType");
                    }
                    else { ViewBag.error = "Failed to Update"; }
                }
            return View(at);
        }

        public ActionResult DeleteSongType(int id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            AudioType at = db.AudioTypes.Find(id);
            Session["AudioType_Id"] = id;
            if (at == null)
            {
                ViewBag.error = "Data Not Found | Technical error";
            }
            return View(at);
        }
        [HttpPost]
        public ActionResult DeleteSongType()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }

            int id = Convert.ToInt32(Session["AudioType_Id"]);
            AudioType at = db.AudioTypes.Find(id);
            
            if (at != null)
            {
                db.AudioTypes.Remove(at);
                int i = db.SaveChanges();
                if (i > 0)
                {
                    return RedirectToAction("AddSongType");
                }
                else { ViewBag.error = "Failed to Update"; }
            }
            return View(at);
        }
        public ActionResult SongInfo()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            
            return View(db.Audios.OrderBy(a=>a.Title).ToList());
        }
        public ActionResult SongCreate()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.AudioType = db.AudioTypes.OrderBy(a=>a.AudioType1).ToList();
            return View();
        }
        [HttpPost]

Music/Controllers/VeeralPatelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Music.Controllers
{
    public class VeeralPatelController : Controller
    {
        // GET: VeeralPatel
        Music_DBEntities db = new Music_DBEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Home()
        {
            MainProfile mp = db.MainProfiles.FirstOrDefault();
            Session["Twitter"] = mp.TwiterLink;
            Session["Facebook"] = mp.FacebookLink;
            Session["Youtube"] = mp.YouTubeLink;
            Session["google+"] = mp.Google_Link;
            return View();
        }

        public ActionResult Photos()
        {
            return View(db.PhotoAlbums.ToList());
        }
        public ActionResult AlbumDetail(int id)
        {
            Session["PhotoAlbum_Id"] = id;
            return View(db.PhotoAlbums.Find(id).PhotoAlbumDetails.ToList());
        }

        public ActionResult Songs(int id=0)
        {
            return View(db.Audios.Where(m=>m.AudioType_Id==id).ToList());
        }

        public ActionResult Videos(int id=0)
        {
            return View(db.Videos.Where(m=>m.VideoType_Id==id).ToList());
        }
        public ActionResult ContactUs()
        {
            MainProfile mp = db.MainProfiles.FirstOrDefault();
            return View(mp);
        }
        [HttpPost]
        public ActionResult ContactUs(string Email, string Name, string Phone, string Message)
        {
            MainProfile mp = db.MainProfiles.FirstOrDefault();
            try
            {
                MailMessage mail = new MailMessage();
                SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");

                mail.From = new MailAddress("jaygandhi933@gmail.com");
                mail.To.Add(Email);
                mail.Subject = "Music Store";
                mail.Body = "Name: " + Name + System.Environment.NewLine + "Contact Number is " + Phone + System.Environment.NewLine + Message;

                SmtpServer.Port = 587;
                SmtpServer.Credentials = new System.Net.NetworkCredential("jaygandhi933@gmail.com", "9033344995jalu");
                SmtpServer.EnableSsl = true;

                SmtpServer.Send(mail);
                ViewBag.msg = "Mail has been sent";
            }
            catch
            {
                ViewBag.error = "Mail has not been sent";
            }
            return View(mp);
        }
 
        public ActionResult AboutUs()
        {
            return View();
        }

    }
}

Music/Views/Shared/Admin_Layout_Page.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Veeral Patel | Music Store</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />

    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- js -->
    <script type="text/javascript" src="~/js/jquery-2.1.4.min.js"></script>
    <script src="~/js/main.js"></script>
    <!-- //js -->
    <!-- font-awesome icons -->
    <link rel="stylesheet" href="css/font-awesome.min.css" />
    <!-- //font-awesome icons -->
    <link rel="stylesheet" href="~/css/flexslider.css" type="text/css" media="screen" property="" />
    <link href="//fonts.googleapis.com/css?family=Varela+Round&subset=hebrew" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>


</head>
<body>
    <div>


        <div class="banner1">
            <div class="container">
                <nav class="navbar navbar-default">
                    <div class="navbar-header navbar-left">
                        <button type="button" class="navbar-toggle collapsed"   data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1 ><a class="navbar-brand" href="~/Admin/Profile" style="font-size:26px;"><span style="font-size:26px;">Viraal </span>Patel</a></h1>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                        <nav class="cl-effect-13" id="cl-effect-13">
                            <ul class="nav navbar-nav" id="menu1">
                                <li id="liAdminProfile"><a href="@Url.Action("Profile","Admin")">Profile</a></li>
                                <li id="liVideoInfo"><a href="@Url.Action("VideoInfo","Admin")">Video Info</a></li>
                                <li id="liSongInfo"><a href="@Url.Action("SongInfo","Admin")">Song Info</a></li>
                                <li id="liAlbumInfo"><a href="@Url.Action("AlbumInfo","Admin")">Album Info</a></li>
                                <li id="liAdmin"><a href="@Url.Action("AdminInfo","Admin")">Admin Info</a></li>
                                <li id=""><a href="@Url.Action("Logout","Admin")">Logout</a></li>
                            </ul>
                            @*<div class="w3_agile_login">
                                <div class="cd-main-header">
                                    <a class="cd-search-trigger" href="#cd-search"> <span></span></a>
                                    <!-- cd-header-buttons -->
                                </div>
                                <div id="cd-search" class="cd-search">
                                    <form action="#" method="post">
                                        <input name="Search" type="search" placeholder="Search...">
                                    </form>
                                </div>
                            </div>*@
                        </nav>
                    </div>
                </nav>
                <div class="mail">
                    <div class="container">
                        <h2 class="agileinfo_header" style="background-color:rgba(255,255,255,0.7); border-radius:10px;">@ViewBag.PageTitle</h2>
                    </div>
                </div>
                <!-- flexSlider -->
                <script defer src="~/js/jquery.flexslider.js"></script>
                <script type="text/javascript">
                    $(window).load(function () {
                        $('.flexslider').flexslider({
                            animation: "slide",
                            start: function (slider) {
                                $('body').removeClass('loading');
                            }
                        });
                    });
                </script>
                <!-- //flexSlider -->
            </div>
        </div>
        @RenderBody()

        <div class="copyright">
            <div class="container">
                @*<div class="w3agile-list">
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><a href="services.html">Services</a></li>
                        <li><a href="icons.html">Codes</a></li>
                        <li><a href="portfolio.html">Portfolio</a></li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                </div>*@
                <div class="agileinfo">
                    <p>© 2017 All Rights Reserved By <a href="@Url.Action("Profile","Admin")">Viraal Patel</a>. Design by Jay Gandhi</p>
                </div>
            </div>
        </div>
        <!-- //copyright -->


        <!-- for bootstrap working -->
        <script src="~/js/bootstrap.js"></script>
        <!-- //for bootstrap working -->
        <!-- stats -->
        <script src="~/js/jquery.waypoints.min.js"></script>
        <script src="~/js/jquery.countup.js"></script>
        <script>
            $('.counter').countUp();
        </script>
        <!-- //stats -->
        <!-- start-smooth-scrolling -->
        <script type="text/javascript" src="~/js/move-top.js"></script>
        <script type="text/javascript" src="~/js/easing.js"></script>
        <script type="text/javascript">
            jQuery(document).ready(function ($) {
                $(".scroll").click(function (event) {
                    event.preventDefault();
                    $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
                });
            });
        </script>
        <!-- start-smooth-scrolling -->
        <!-- here stars scrolling icon -->
        <script type="text/javascript">
            $(document).ready(function () {
                /*
                    var defaults = {
                    containerID: 'toTop', // fading element id
                    containerHoverID: 'toTopHover', // fading element hover id
                    scrollSpeed: 1200,
                    easingType: 'linear'
                    };
                */

                $().UItoTop({ easingType: 'easeOutQuart' });

            });
        </script>
        <!-- //here ends scrolling icon -->
        <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 0;"></span>To Top</a>

    </div>
</body>
</html>

Music/Views/Shared/Outer_LayoutPage_Visit_Menu.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Veeral Patel | Music Store</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />

    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- js -->
    <script type="text/javascript" src="~/js/jquery-2.1.4.min.js"></script>
    <script src="~/js/main.js"></script>
    <!-- //js -->
    <!-- font-awesome icons -->
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link href="~/css/flexslider.css" rel="stylesheet" />
    <!-- //font-awesome icons -->
    <link rel="stylesheet" href="~/css/flexslider.css" type="text/css" media="screen" property="" />
    <link href="//fonts.googleapis.com/css?family=Varela+Round&subset=hebrew" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>


</head>
<body>
    <div>
@{
    Music.Music_DBEntities db = new Music_DBEntities();
}

        <div class="banner1">
            <div class="container">
                <nav class="navbar navbar-default">
                    <div class="navbar-header navbar-left">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1><a class="navbar-brand" href="~/Admin/Profile" style="font-size:26px;"><span style="font-size:26px;">Viraal </span>Patel</a></h1>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                        <nav class="cl-effect-13" id="cl-effect-13">
                            <ul class="nav navbar-nav" id="menu1">
                                <li id="liHome"><a href="@Url.Action("Home","VeeralPatel")">Home</a></li>
                                <li id="liPhotos"><a href="@Url.Action("Photos","VeeralPatel")">Photos</a></li>
                                <li class="dropdown" id="liSongs">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Songs<b class="caret"></b></a>
                                    <ul class="dropdown-menu agile_short_dropdown">
                                        @foreach (var l in db.AudioTypes.OrderBy(a=>a.AudioType1).ToList())
                                        {
                                            <li><a href="@Url.Action("Songs", "VeeralPatel", new {id=l.AudioType_Id })">@l.AudioType1</a></li>
                                        }
                                    </ul>
                                </li>

                                <li class="dropdown" id="liVideos">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Videos<b class="caret"></b></a>
                                    <ul class="dropdown-menu agile_short_dropdown">
                                        @foreach (var l in db.VideoTypes.OrderBy(a=>a.VideoType1).ToList())
                                        {
                                            <li><a href="@Url.Action("Videos", "VeeralPatel", new {id=l.VideoType_Id })">@l.VideoType1</a></li>
                                        }
                                    </ul>
                                </li>

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
                                    <ul class="dropdown-menu agile_short_dropdown">
                                        <li><a href="#">Biography</a></li>
                                        <li><a href="#">About Us</a></li>
                                        <li><a href="@Url.Action("ContactUs","VeeralPatel")">Contact Us</a></li>
                                    </ul>
                                </li>
                            </ul>
                            @*<div class="w3_agile_login">
                                    <div class="cd-main-header">
                                        <a class="cd-search-trigger" href="#cd-search"> <span></span></a>
                                        <!-- cd-header-buttons -->
                                    </div>
                                    <div id="cd-search" class="cd-search">
                                        <form action="#" method="post">
                                            <input name="Search" type="search" placeholder="Search...">
                                        </form>
                                    </div>
                                </div>*@
                        </nav>
                    </div>
                </nav>
                
                <!-- flexSlider -->
                <script defer src="~/js/jquery.flexslider.js"></script>
                <script type="text/javascript">
                    $(window).load(function () {
                        $('.flexslider').flexslider({
                            animation: "slide",
                            start: function (slider) {
                                $('body').removeClass('loading');
                            }
                        });
                    });
                </script>
                <!-- //flexSlider -->
            </div>
        </div>
        @RenderBody()

        <div class="copyright">
            <div class="container">
                @*<div class="w3agile-list">
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><a href="services.html">Services</a></li>
                        <li><a href="icons.html">Codes</a></li>
                        <li><a href="portfolio.html">Portfolio</a></li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                </div>*@
                <div class="agileinfo">
                    <div class="footer-icons">
                        <div class="col-md-6">
                            <ul>
                                <li><a href="@Session["Twitter"]" class="twitter"><i class="fa fa-twitter"></i></a><span>Twitter</span></li>
                                <li><a href="@Session["Facebook"]" class="twitter facebook"><i class="fa fa-facebook"></i></a><span>Facebook</span></li>
                                <li><a href="@Session["google+"]" class="twitter chrome"><i class="fa fa-google-plus"></i></a><span>Google +</span></li>
                                <li><a href="@Session["Youtube"]" class="twitter dribbble"><i class="fa fa-youtube" aria-hidden="true" style="font-size:25px; color:white;"></i></a><span>You Tube</span></li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <p style="text-align:center;">© 2017 All Rights Reserved <a href="#">Veeral Patel</a>. Design by Jay Gandhi</p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- //copyright -->
        <!-- for bootstrap working -->
        <script src="~/js/bootstrap.js"></script>
        <!-- //for bootstrap working -->
        <!-- stats -->
        <script src="~/js/jquery.waypoints.min.js"></script>
        <script src="~/js/jquery.countup.js"></script>
        <script>
            $('.counter').countUp();
        </script>
        <!-- //stats -->
        <!-- start-smooth-scrolling -->
        <script type="text/javascript" src="~/js/move-top.js"></script>
        <script type="text/javascript" src="~/js/easing.js"></script>
        <script type="text/javascript">
            jQuery(document).ready(function ($) {
                $(".scroll").click(function (event) {
                    event.preventDefault();
                    $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
                });
            });
        </script>
        <!-- start-smooth-scrolling -->
        <!-- here stars scrolling icon -->
        <script type="text/javascript">
            $(document).ready(function () {
                /*
                    var defaults = {
                    containerID: 'toTop', // fading element id
                    containerHoverID: 'toTopHover', // fading element hover id
                    scrollSpeed: 1200,
                    easingType: 'linear'
                    };
                */

                $().UItoTop({ easingType: 'easeOutQuart' });

            });
        </script>
        <!-- //here ends scrolling icon -->
        <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 0;"></span>To Top</a>

    </div>
</body>
</html>